### ISSUE TITLE
Which are the specific codes of mix3d to apply to another dataset or model?

### ISSUE THREAD

**Issue by whuhxb** [kumuji/mix3d#15]
Hi @kumuji @JonasSchult @francisengelmann 

Which are the specific codes of mix3d to apply to anther dataset or model?  Could you please help me out? Thanks a lot.

Best regards.
Xiaobing

**Comment by kumuji** [comment]
Hi!

It depends on your setup, you could load and merge a separate point cloud in your dataset class https://github.com/kumuji/mix3d/blob/5b9da0f6418c26c2d4b336997cc0bab9836b8fee/SpatioTemporalSegmentation-ScanNet.patch#L109, or merge batch entries at a dataloading stage https://github.com/kumuji/mix3d/blob/5b9da0f6418c26c2d4b336997cc0bab9836b8fee/mix3d/datasets/utils.py#L77. 

Mainly, you want to augment both point clouds individually, move them close and concatenate.

**Comment by whuhxb** [comment]
@kumuji 
OK. If just use one dataset to augment, choose this, righ? or merge batch entries at a dataloading stage?
