### ISSUE TITLE
Why downsample with kernelsize=2

### ISSUE THREAD

**Issue by kwwcv** [kumuji/mix3d#18]
Hi,
I'm new in 3D, can anyone tell me why using kernelsize=2 instead of 3 for downsample operation in backbones, e.g., resunet? Thanks in advance.

**Comment by kumuji** [comment]
Hi @kwwcv, sadly, I can't answer this question.  I suggest contacting Chris Choy about the details. I used model implementation from [his repository](https://github.com/chrischoy/SpatioTemporalSegmentation-ScanNet) as it is.
