### ISSUE TITLE
How can the points in the two scenes not overlap during the mixing process?

### ISSUE THREAD

**Issue by mrsempress** [kumuji/mix3d#23]
How can the points in the two scenes not overlap during the mixing process? If two points of a random mix fall in the same area(xyz), whether it is randomly marked as one of category or whether the mix operation has special treatment.

**Comment by kumuji** [comment]
Hi @mrsempress,

Points in a voxel can overlap during mixing. As far as I know, the MinkowskiEngine's implementation of voxelization just picks a random point in the region. We haven't studied the effect of special treatment of overlapping points on semantic segmentation performance, although we planned to go in that direction in the early stages.

Best regards,
Alexey
