### ISSUE TITLE
pre-trained models

### ISSUE THREAD

**Issue by jason718** [kumuji/mix3d#4]
Can you release the pre-trained models that get these testing numbers in paper?

**Comment by kumuji** [comment]
@jason718 , hi!

We do not plan to outsource trained models. Buy you can find the [patch file](https://github.com/kumuji/mix3d/blob/master/SpatioTemporalSegmentation-ScanNet.patch) to modify the original MinkowskiNet repository and get similar result.

Best,
Alexey
