### ISSUE TITLE
Applying data augmentation to another model

### ISSUE THREAD

**Issue by MasatoSaeki** [kumuji/mix3d#6]
Thank you very much for your work.
When I apply data augmentation to another model using semantickitti, which module(file) should I use?
I am sorry. The paper says that it is easy to incorporate into existing code bases, but I did not understand it.

**Comment by kumuji** [comment]
It is a little bit hard to provide the exact code for your application, but simply speaking you want to sample an additional point cloud in the dataset `__getitem__` ([similar to this](https://github.com/kumuji/mix3d/blob/f25d4075e8603b09e8aa2dc90f92b426f3a87463/SpatioTemporalSegmentation-ScanNet.patch#L109)) move them both closer to center and than concatenate them together.

**Comment by MasatoSaeki** [comment]
I understand it a little.
Thanks to your reply, I can take a new step forword.
