### ISSUE TITLE
Performance improvement gap between val and test set on ScanNet

### ISSUE THREAD

**Issue by xiaodongww** [kumuji/mix3d#7]
Hi, thanks for your job. I have a question about the performance on the ScanNet dataset.

I find that Mix3D augmentation applied on MinkowskiNet improves 1.2% (73.6 vs 72.4) mIoU on the  ScanNet validation set reported in Table1.  However, on the test set, Mix3D is 4.5% higher (78.1 vs 73.6).   Do you know why Mix3D's performance is much better than  MinkowskiNet on the test set? 

Another question is about `test time augmentation` mentioned in Part 4.1 of the paper.  What is test time augmentation? Do you mean augmenting one scene multiple times and averaging the semantic predictions to get a better result in the test time? 

Looking forward to your reply! Thanks!

**Comment by kumuji** [comment]
Hi!

On validation set the only difference is mixing. For benchmarks submissions we applied multiple tricks to push the scores. You can find detailed information in the [paper and supplementary](https://arxiv.org/abs/2110.02210).

TTA - test time augmentation. We slightly augment test samples and average the predictions to get the final prediction. You are correct =)  

Best,
Alexey
