### ISSUE TITLE
Do you provide point cloud based method like kpconv's code

### ISSUE THREAD

**Issue by yuchenlichuck** [kumuji/mix3d#9]

**Comment by yuchenlichuck** [comment]
In [kpconv_pytorch_mix3d.patch](https://github.com/kumuji/mix3d/blob/master/kpconv_pytorch_mix3d.patch)?

**Comment by yuchenlichuck** [comment]
Meanwhile, where is the code doing voting strategies

**Comment by kumuji** [comment]
Yes, the code for kpconv is in the patch.
We do not provide the code for submission, but we wrote about all the tricks we applied for the submission in the supplementary.
